# config context path to "/" by setting an empty string
server:
  contextPath: /
  hostname: http://127.0.1.1:8089

hostname: http://127.0.1.1:8089
# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG